name: Actions

on:
  push: { branches: [main]}

jobs:
  testRunner:
    name: Test all modes
    runs-on: ubuntu-latest

    steps:
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ./
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  buildAndroid:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android